### PR TITLE
Use cowboy 1.1.2

### PR DESCRIPTION
**Pull request by cxa**

### CODE REVIEW

**Comment by 5HT** [comment]
Seems like you prepered a lot of PR, I'll accept them all! 🥇

**Comment by cxa** [comment]
Ah, I don't have any plan, I just want to let n2o master works with nitro master.

I'm using n2o for a personal project, the large purpose is learning Erlang, what I'm good at is front-end, so my pull requests will be more related to front-end things, which'll be very subtle.

By the way, I am not confident if there has any preblem for upgrading cowboy to 1.1.2, so I close this pull request, and which doesn't affect using n2o.

**Comment by 5HT** [comment]
So you didn't check working 1.1.2 version?

**Comment by cxa** [comment]
I'm using 1.1.2 and found no problem, but my project is very small, may be there're lots of case being not covered.

**Comment by 5HT** [comment]
Not really, see https://github.com/synrc/n2o/blob/master/src/endpoints/cowboy/n2o_cowboy.erl

**Pull request closed without merging**
